fir/urls.py
from pkgutil import find_loader
from django.conf.urls import include, url
from django.contrib import admin

from fir.config.base import INSTALLED_APPS
from incidents import views

# urls for core FIR components
urlpatterns = [
    url(r'^incidents/', include('incidents.urls', namespace='incidents')),
    url(r'^search/$', views.search, name='search'),
    url(r'^events/', include('incidents.custom_urls.events', namespace='events')),
    url(r'^login/', views.user_login, name='login'),            # have a "main module"
    url(r'^logout/', views.user_logout, name='logout'),         # main module
    url(r'^stats/', include('incidents.custom_urls.stats', namespace='stats')),
    url(r'^ajax/', include('incidents.custom_urls.ajax', namespace='ajax')),
    url(r'^user/', include('incidents.custom_urls.user', namespace='user')),
    url(r'^dashboard/', include('incidents.custom_urls.dashboard', namespace='dashboard')),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^$', views.dashboard_main),
]

for app in INSTALLED_APPS:
    if app.startswith('fir_'):
        app_name = app[4:]
        app_urls = '{}.urls'.format(app)
        if find_loader(app_urls):
            urlpatterns.append(url('^{}/'.format(app_name), include(app_urls, namespace=app_name)))

fir_api/urls.py
from django.conf.urls import include, url
from rest_framework import routers
from rest_framework.authtoken import views as token_views

from fir_api import views

# automatic URL routing for API
# include login URLs for the browsable API.
router = routers.DefaultRouter(trailing_slash=False)

router.register(r'users', views.UserViewSet)
router.register(r'incidents', views.IncidentViewSet)
router.register(r'artifacts', views.ArtifactViewSet)
router.register(r'files', views.FileViewSet)

# urls for core FIR components
urlpatterns = [
    url(r'^', include(router.urls)),
    url(r'^token/', token_views.obtain_auth_token),
]

incidents/urls.py
from django.conf.urls import url

from incidents import views

urlpatterns = [
    url(r'^$', views.index, {'is_incident': True}, name='index'),
    url(r'^all/$', views.incidents_all, name='all'),
    url(r'^(?P<incident_id>\d+)/$', views.details, name='details'),
    url(r'^(?P<incident_id>\d+)/followup/$', views.followup, name='followup'),
    url(r'^(?P<incident_id>\d+)/comment/$', views.comment, name='comment'),
    url(r'^(?P<incident_id>\d+)/comment/(?P<comment_id>\d+)/delete/$', views.delete_comment, name='delete_comment'),
    url(r'^(?P<incident_id>\d+)/edit/$', views.edit_incident, name='edit'),
    url(r'^(?P<incident_id>\d+)/delete/$', views.delete_incident, name='delete'),
    url(r'^(?P<incident_id>\d+)/status/(?P<status>[OBC])$', views.change_status, name='change_status'),
    url(r'^(?P<incident_id>\d+)/attribute$', views.add_attribute, name='add_attribute'),
    url(r'^(?P<incident_id>\d+)/attribute/(?P<attribute_id>\d+)/delete/$', views.delete_attribute, name='delete_attribute'),
]

incidents/models.py
# -*- coding: utf-8 -*-
import datetime

from django.db.models.signals import post_save
from django.dispatch import Signal, receiver
from django.db import models
from django.forms import ModelForm
from django import forms
from django.contrib.auth.models import User
from django.utils.translation import ugettext_lazy as _
from django.conf import settings

from treebeard.mp_tree import MP_Node

from fir_artifacts import artifacts
from fir_artifacts.models import Artifact, File
from fir_plugins.models import link_to
from incidents.authorization import tree_authorization, AuthorizationModelMixin

STATUS_CHOICES = (
    ("O", _("Open")),
    ("C", _("Closed")),
    ("B", _("Blocked")),
)

SEVERITY_CHOICES = (
    (1, '1'),
    (2, '2'),
    (3, '3'),
    (4, '4'),
)

LOG_ACTIONS = (
    ("D", "Deleted"),
    ("C", "Created"),
    ("U", "Update"),
    ("LI", "Logged in"),
    ("LO", "Logged out"),
)

CONFIDENTIALITY_LEVEL = (
    (0, "C0"),
    (1, "C1"),
    (2, "C2"),
    (3, "C3"),
)

# Special Model class that handles signals


model_created = Signal(providing_args=['instance'])
model_updated = Signal(providing_args=['instance'])
model_status_changed = Signal(providing_args=['instance', 'previous_status'])


class FIRModel:
    def done_creating(self):
        model_created.send(sender=self.__class__, instance=self)

    def done_updating(self):
        model_updated.send(sender=self.__class__, instance=self)


# Profile ====================================================================


class Profile(models.Model):
    user = models.OneToOneField(User)
    incident_number = models.IntegerField(default=50)
    hide_closed = models.BooleanField(default=False)

    def __unicode__(self):
        return u"Profile for user '{}'".format(self.user)


# Audit trail ================================================================


class Log(models.Model):
    who = models.ForeignKey(User, null=True, blank=True)
    what = models.CharField(max_length=100, choices=STATUS_CHOICES)
    when = models.DateTimeField(auto_now_add=True)
    incident = models.ForeignKey('Incident', null=True, blank=True)
    comment = models.ForeignKey('Comments', null=True, blank=True)

    def __unicode__(self):
        if self.incident:
            return u"[%s] %s %s (%s)" % (self.when, self.what, self.incident, self.who)
        elif self.comment:
            return u"[%s] %s comment on %s (%s)" % (self.when, self.what, self.comment.incident, self.who)
        else:
            return u"[%s] %s (%s)" % (self.when, self.what, self.who)


class LabelGroup(models.Model):
    name = models.CharField(max_length=50)

    def __unicode__(self):
        return self.name


class Label(models.Model):
    name = models.CharField(max_length=50)
    group = models.ForeignKey(LabelGroup)

    def __unicode__(self):
        return "%s" % (self.name)


class BusinessLine(MP_Node, AuthorizationModelMixin):
    name = models.CharField(max_length=100)

    def __unicode__(self):
        parents = list(self.get_ancestors())
        parents.append(self)
        return u" > ".join([bl.name for bl in parents])

    class Meta:
        verbose_name = _('business line')

    def get_incident_count(self, query):
        incident_count = self.incident_set.filter(query).distinct().count()
        incident_count += Incident.objects.filter(query).filter(
            concerned_business_lines__in=self.get_descendants()).distinct().count()
        return incident_count


class AccessControlEntry(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, verbose_name=_('user'), on_delete=models.CASCADE)
    business_line = models.ForeignKey(BusinessLine, verbose_name=_('business line'), related_name='acl')
    role = models.ForeignKey('auth.Group', verbose_name=_('role'))

    def __unicode__(self):
        return _("{} is {} on {}").format(self.user, self.role, self.business_line)

    class Meta:
        verbose_name = _('access control entry')
        verbose_name_plural = _('access control entries')


class BaleCategory(models.Model):
    name = models.CharField(max_length=200)
    description = models.TextField(blank=True, null=True)
    category_number = models.IntegerField()
    parent_category = models.ForeignKey('BaleCategory', null=True, blank=True)

    class Meta:
        verbose_name_plural = "Bale categories"

    def __unicode__(self):
        if self.parent_category:
            return "(%s > %s) %s" % (self.parent_category.category_number, self.category_number, self.name)
        else:
            return "(%s) %s" % (self.category_number, self.name)


class IncidentCategory(models.Model):
    name = models.CharField(max_length=100)
    bale_subcategory = models.ForeignKey(BaleCategory)
    is_major = models.BooleanField(default=False)

    class Meta:
        verbose_name_plural = "Incident categories"

    def __unicode__(self):
        return self.name


# Core models ================================================================

@tree_authorization(fields=['concerned_business_lines', ], tree_model='incidents.BusinessLine',
                    owner_field='opened_by', owner_permission=settings.INCIDENT_CREATOR_PERMISSION)
@link_to(File)
@link_to(Artifact)
class Incident(FIRModel, models.Model):
    date = models.DateTimeField(default=datetime.datetime.now, blank=True)
    is_starred = models.BooleanField(default=False)
    subject = models.CharField(max_length=256)
    description = models.TextField()
    category = models.ForeignKey(IncidentCategory)
    concerned_business_lines = models.ManyToManyField(BusinessLine, blank=True)
    main_business_lines = models.ManyToManyField(BusinessLine, related_name='incidents_affecting_main', blank=True)
    detection = models.ForeignKey(Label, limit_choices_to={'group__name': 'detection'}, related_name='detection_label')
    severity = models.IntegerField(choices=SEVERITY_CHOICES)
    is_incident = models.BooleanField(default=False)
    is_major = models.BooleanField(default=False)
    actor = models.ForeignKey(Label, limit_choices_to={'group__name': 'actor'}, related_name='actor_label', blank=True,
                              null=True)
    plan = models.ForeignKey(Label, limit_choices_to={'group__name': 'plan'}, related_name='plan_label', blank=True,
                             null=True)
    status = models.CharField(max_length=20, choices=STATUS_CHOICES, default=_("Open"))
    opened_by = models.ForeignKey(User)
    confidentiality = models.IntegerField(choices=CONFIDENTIALITY_LEVEL, default='1')

    def __unicode__(self):
        return self.subject

    def is_open(self):
        return self.get_last_action != "Closed"

    def close_timeout(self):
        previous_status = self.status
        self.status = 'C'
        self.save()
        model_status_changed.send(sender=Incident, instance=self, previous_status=previous_status)

        c = Comments()
        c.comment = "Incident closed (timeout)"
        c.date = datetime.datetime.now()
        c.action = Label.objects.get(name='Closed', group__name='action')
        c.incident = self
        c.opened_by = User.objects.get(username='cert')
        c.save()

    def get_last_comment(self):
        return self.comments_set.order_by('-date')[0]

    def get_last_action(self):
        c = self.comments_set.order_by('-date')[0]

        action = "%s (%s)" % (c.action, c.date.strftime("%Y %d %b %H:%M:%S"))

        return action

    def concerns_business_line(self, bl_string):
        for bl in self.concerned_business_lines.all():
            if bl.name == bl_string:
                return bl.name
            if bl.get_ancestors().filter(name=bl_string).count():
                return bl.name
        return False

    def get_business_lines_names(self):
        return ", ".join([b.name for b in self.concerned_business_lines.all()])

    def refresh_main_business_lines(self):
        mainbls = set()
        for bl in self.concerned_business_lines.all():
            mainbls.add(bl.get_root())
        self.main_business_lines = list(mainbls)

    def refresh_artifacts(self, data=""):
        if data == "":
            coms = self.comments_set.all()

            data = self.description
            for c in coms:
                data += "\n" + c.comment

        found_artifacts = artifacts.find(data)

        artifact_list = []
        for key in found_artifacts:
            for a in found_artifacts[key]:
                artifact_list.append((key, a))

        db_artifacts = Artifact.objects.filter(value__in=[a[1] for a in artifact_list])

        exist = []

        for a in db_artifacts:
            exist.append((a.type, a.value))
            if self not in a.incidents.all():
                a.incidents.add(self)

        new_artifacts = list(set(artifact_list) - set(exist))
        all_artifacts = list(set(artifact_list))

        for a in new_artifacts:
            new = Artifact(type=a[0], value=a[1])
            new.save()
            new.incidents.add(self)

        for a in all_artifacts:
            artifacts.after_save(a[0], a[1], self)

    class Meta:
        permissions = (
            ('handle_incidents', 'Can handle incidents'),
            ('report_events', 'Can report events'),
            ('view_incidents', 'Can view incidents'),
            ('view_statistics', 'Can view statistics'),
        )


class Comments(models.Model):
    date = models.DateTimeField(default=datetime.datetime.now, blank=True)
    comment = models.TextField()
    action = models.ForeignKey(Label, limit_choices_to={'group__name': 'action'}, related_name='action_label')
    incident = models.ForeignKey(Incident)
    opened_by = models.ForeignKey(User)

    class Meta:
        verbose_name_plural = 'comments'

    def __unicode__(self):
        return u"Comment for incident %s" % self.incident.id

    @classmethod
    def create_diff_comment(cls, incident, data, user):
        comments = ''
        for key in data:

incidents/templates/stats/attributes.html
{% extends 'base.html' %}
{% load i18n %}
{% load staticfiles %}

{% block custom_js_top %}
<script src="{% static "js/d3.v3.min.js" %}"></script>
<script src="{% static "js/nv.d3.min.js" %}"></script>
{% endblock %}

{% block custom_js %}
<script src="{% static "js/bootstrap-datetimepicker.min.js" %}"></script>
<script src="{% static "js/excellentexport.js" %}"></script>
<script src="{% static "select/select2.min.js" %}"></script>
<script src="{% static "custom_js/export.js" %}"></script>

<script>
function refresh_stats() {
	serialized = $("#attributes").serialize();

	function date_if_needed(date) {
		if (typeof(date) != "object") {
			return new Date(date);
		}
		else {
			return date;
		}
	}

	function customTimeFormat(d) {
		d = date_if_needed(d);
		prefix = "";

		if (d.getUTCMilliseconds()) { format = ".%L"; }
		else if (d.getUTCSeconds()) { format = ":%S"; }
		else if (d.getUTCMinutes()) { format = "%H:%M"; }
		else if (d.getUTCHours()) { format = "%d %Hh"; }
		else if (d.getUTCDate() != 1 && d.getUTCDay() != 0) { format = "%a %d" }
		else if (d.getUTCDate() != 1) { format = "%U"; prefix = "W" }
		else if (d.getUTCMonth()) { format = "%B"; }
		else { format = "%Y"; }

		format = d3.time.format.utc(format);

		if (prefix == "W") {
			w = parseInt(format(d)) + 1;
			return prefix + w;
		}
		else {
			return prefix + format(d);
		}
	}

	// Update main statistics
	$.getJSON('/stats/data/attributes/basic/?' + serialized, function (data) {
		var main = $('#main_statistics');
		var text = "{% trans 'Incidents count:' %}" + ' ' + data.incidents + ' / ' + "{% trans 'With attribute set:' %}" + ' ' + data.with_attribute;

		for (attribute in data.attributes) {
			for (type in data.attributes[attribute]) {
				var a = $('#attribute_' + attribute);
				var unit = a.attr('data-unit');
				text = text + '<br />' + type + ' ' + attribute + ': ' + data.attributes[attribute][type];
				if (unit != 'count') {
					text = text + ' ' + unit;
				}
			}
		}

		main.html('<h4>' + text + '</h4>');
	});

	// Update statistics over time
	$.getJSON('/stats/data/attributes/over_time/?' + serialized, function(data) {
		$('#attribute_over_time svg').show();
		$('#attribute_over_time svg').empty();

		nv.addGraph(function () {
			var chart = nv.models.linePlusBarChart()
				.margin({top: 30, right: 90, bottom: 60, left: 90})
				.color(d3.scale.category10().range())
				.interpolate('monotone');

			chart.lines.xScale(d3.time.scale.utc());
			chart.bars.xScale(d3.time.scale.utc());

			// Display labels on axis
			chart.xAxis.axisLabel('Time').showMaxMin(false).tickFormat(customTimeFormat);

			var y1Axis = $('[name="bars"] :selected').text();
			var unit = $('[name="bars"] :selected').attr('data-unit');
			if (unit != undefined && unit != 'count') {
				y1Axis = y1Axis + ' (in ' + unit + ')';
			}
			chart.y1Axis.axisLabel(y1Axis);

			var y2Axis = ''
			unit = ''
			$('.attribute :checked').each(function (index) {
				if (index != 0) {
					y2Axis = y2Axis + ', ';
				}
				else {
					unit = $(this).attr('data-unit');
				}
				y2Axis = y2Axis + $(this).attr('data-name');
			});
			if (unit != undefined && unit != 'count') {
				y2Axis = y2Axis + ' (in ' + unit + ')';
			}
			chart.y2Axis.axisLabel(y2Axis);


			d3.select('#attribute_over_time svg')
				.datum(data)
				.transition().duration(300)
				.call(chart);

			nv.utils.windowResize(chart.update);

			return chart;
		});
	});

	// Display table of matching incidents
	$.getJSON('/stats/data/attributes/table/?' + serialized, function(data) {
		// Clear all content
		var incidents_table = $('#incidents_table');
		incidents_table.empty();

		// Display correct incidents number
		$('#incident_count').text(data.length);

		// Create headers
		var table = $('<table id="incident_table" class="table table-hover table-condensed sortable followup-table">');
		var thead = $('<thead>');
		var tbody = $('<tbody>');
		var tr = $('<tr />');
		tr.append('<th>'+'{% trans "Date" %}'+'</th>');
		tr.append('<th>'+'{% trans "Category" %}'+'</th>');
		tr.append('<th>'+'{% trans "Subject" %}'+'</th>');
		tr.append('<th>'+'{% trans "Business&nbsp;Lines" %}'+'</th>');
		for (attribute in data[0].attributes) {
			if (data[0].attributes.hasOwnProperty(attribute)) {
				tr.append('<th>' + attribute + '</th>');
			}
		}
		thead.append(tr);
		table.append(thead);

		// Create body
		$.each(data, function(key, incident) {
			tr = $('<tr />');
			tr.append("<td>"+moment(incident.date, 'YYYY-MM-DD HH:mm').format('YYYY-MM-DD HH:mm')+"</td>");
			tr.append("<td>"+incident.category+"</td>");
			tr.append("<td><a href='"+incident.url+"'>"+incident.subject+"</a></td>");
			tr.append("<td>"+incident.business_lines_names+"</td>");
			for (attribute in incident.attributes) {
				if (incident.attributes.hasOwnProperty(attribute)) {
					tr.append("<td>"+incident.attributes[attribute]+"</td>");
				}
			}
			tbody.append(tr);
		});
		table.append(tbody);
		incidents_table.append(table);
	});
}

$(document).ready(function() {
  $("#id_concerned_business_lines").select2({ dropdownAutoWidth: true });
  $('#severity_comparator').select2({minimumResultsForSearch: -1});
  $('#id_status').select2({minimumResultsForSearch: -1});
  $('#id_detection').select2({minimumResultsForSearch: -1});
  $('#id_severity').select2({minimumResultsForSearch: -1});
  $('#id_actor').select2({minimumResultsForSearch: -1});
  $('#id_plan').select2({minimumResultsForSearch: -1});
  $('#id_confidentiality').select2({minimumResultsForSearch: -1});
  $('#bars').select2({minimumResultsForSearch: -1});

  $('#from_date').datetimepicker({
    format: 'yyyy-mm-dd hh:ii',
    minView: 1,
    autoclose: true,
    todayBtn: true,
    weekStart: 1
  });

  $('#to_date').datetimepicker({
    format: 'yyyy-mm-dd hh:ii',
    minView: 1,
    autoclose: true,
    todayBtn: true,
    weekStart: 1
  });

  $('#refresh').click(function (event) {
  	refresh_stats();
  	event.preventDefault();
  });

  // Only allow selection of several attributes if they have the same unit
  $('.attribute :checkbox').change(function () {
  	if ($(this).is(':checked')) {
  		unit = $(this).attr('data-unit');
	  	$('.attribute :checkbox').each(function (i) {
	  		if ($(this).attr('data-unit') != unit) {
	  			$(this).prop('disabled', true);
	  		}
	  	});
  	}
  	else if ($('.attribute :checkbox:checked').length == 0) {
  		$('.attribute :checkbox').each(function (i) {
  			$(this).prop('disabled', false);
  		});
  	}
  });
});
</script>
{% endblock %}

{% block custom_css %}
<link href="{% static "select/select2.css" %}" rel="stylesheet"/>
<link href="{% static "css/bootstrap-datetimepicker.min.css" %}" rel="stylesheet"/>
<link href="{% static "css/nv.d3.min.css" %}" rel="stylesheet" />

<style>

/* form */

.form-group {
	margin: 0 5px 10px 5px;
}

#search-bar {
    margin: 0;
}

fieldset.fields {
  float:left;
  width:300px;
}

.checkbox {
  margin-top: 0;
}

.checkbox+.checkbox {
  margin-top: 0;
}

fieldset.categories {
  float:left;
}

fieldset.bars {
	clear: both;
	float: left;
	width: 300px;
	margin-top: 15px;
}

fieldset.attributes {
	float: left;
	margin-top: 15px;
}

div.attribute label {
	display: inline-block;
	margin-right: 15px;
}

.categories label.checkbox {
  width:110px;
  float:left;
  padding-top: 0px !important;
  margin-bottom: 5px;
}

div.categories {
  width:360px;
  height:200px;
}

#severity_comparator {
  width:20px;
}

#sandbox input.date {
  width:90px;
}

.btn-mini {
  margin-top:0px;
}

.separator {
  clear:both;
  margin:30px 0 30px 0;
}

h4 .smaller {
  font-size: 10px;
  font-weight: normal;
}

input.date {
	width: 120px;
	font-size: 11px;
}

@media print {
	.nv-point-paths {
		display: none;
	}
}

.clear {
	clear: both;
}

</style>
{% endblock %}

{% block content %}
<form action="{% url 'stats:attributes' %}" method='post' id='attributes' class='noprint'>

  <fieldset class='fields'>

  <div style='margin-top:0;float:left' class='form-group'>
    <label for="from_date" class="control-label">{% trans "From" %}</label>
    <div class='controls'>
      <input class='date form-control' id="from_date" name="from_date" type="text" value="{{ start }}"/>
    </div>
  </div>

  <div style='margin-top:0' class='form-group'>
    <label for="to_date" class="control-label">{% trans "To" %}</label>
    <div class='controls'>
      <input class='date form-control' id="to_date" name="to_date" type="text" value="{{end}}" />
    </div>
  </div>

  <div class='form-group'>
    <label for="id_detection" class="control-label">{% trans "Detection" %}</label>
    <div class='controls'>
      {{ form.detection }}
    </div>
  </div>

  <div class='form-group'>
    <label for="id_severity" class="control-label">{% trans "Severity" %}</label>
    <div class='controls'>
      <select name='severity_comparator' id='severity_comparator'>
        <option value="et">=</option>
        <option value="lt">&lt;</option>
        <option value="lte">&lt;=</option>
        <option value="gt">&gt;</option>
        <option value="gte">&gt;=</option>
      </select>
      {{ form.severity }}
    </div>
  </div>

  </fieldset>
  <fieldset class='categories'>
    <div class='form-group'>
      <label for="id_category" class="control-label">{% trans "Categories" %}</label>
      <div class='controls categories checkbox'>
        {% for c in categories %}
          <label class="checkbox">
            <input type="checkbox" name="category_selection" {% if c.id in categories_checked %}checked='checked'{% endif %} value="{{c.id}}">{{c.name}}
          </label>
        {% endfor %}
      </div>
    </div>
    </fieldset>

    <fieldset class='businessline'>
    	<div class='form-group'>
			<label for="id_concerned_business_lines" class="control-label">{% trans "Business lines" %}</label>
	  		<div class='controls' id='concerned_business_lines'>
				{{ form.concerned_business_lines }}
	  		</div>
	  	</div>

		<div class='form-group checkbox'>
      		<label class="checkbox">
				<input type="checkbox" name="is_incident" value="incident"> {% trans "Incidents only" %}
      		</label>

      		<label class="checkbox">
				<input type="checkbox" name="is_major" value="major"> {% trans "Major incidents only" %}
      		</label>
      	</div>

    </fieldset>

  <fieldset class='bars'>
  	<div class='form-group'>
		<label for="bars" class="control-label">{% trans "Bars" %}</label>
    	<div class='controls'>
	      	<select name='bars' id='bars'>
				<option value="0">{% trans "Incidents" %}</option>
	        	{% for attribute in attributes %}
	        		<option value="{{attribute.id}}" data-unit="{{attribute.unit}}">{{attribute.name}}</option>
	        	{% endfor %}
	      	</select>
	    </div>
	</div>

	<div class='form-group'>
		<div class="checkbox">
		    <label class="checkbox">
				<input type="checkbox" name="only_with_attribute" checked="checked" /> {% trans "Only incidents with attribute set" %}
	      	</label>

		    <label class="checkbox">
				<input type="checkbox" name="total" value="total" checked="checked"> {% trans "Total" %}
	      	</label>

	      	<label class="checkbox">
				<input type="checkbox" name="average" value="average"> {% trans "Average" %}
	      	</label>

	      	<label class="checkbox">
				<input type="checkbox" name="deviation" value="deviation"> {% trans "Standard Deviation" %}
	      	</label>
	    </div>
	</div>
  </fieldset>
  <fieldset class='attributes'>
  	<div class='form-group'>
		<label for="id_attribute" class="control-label">{% trans "Attributes" %}</label>
  		<div class='controls attribute checkbox'>
  		{% for attribute in attributes %}
  			<label class='checkbox'>
  				<input type='checkbox' name='attribute_selection' value='{{attribute.id}}' id='attribute_{{attribute.name}}' data-name='{{attribute.name}}' data-unit='{{attribute.unit}}' />
  				{{ attribute.name }}
  			</label>
  		{% endfor %}
  		</div>
  	</div>
  </fieldset>

  {% csrf_token %}
  <div class='clear'>
	<button class="btn btn-primary" type="button" id="refresh">{% trans "Go" %}</button>
  </div>

</form>


<div id='main_statistics'></div>

<div class='graph' style='width: 1000px;'>
	<h2>{% trans "Over time" %}</h2>
	<div class='graph' id='attribute_over_time'>
		<svg height="500px" style="display: none;" />
	</div>
</div>

<h2>{% trans "Matching incidents" %} (<span id='incident_count'>0</span>)</h2>
<div>Export to <a download="incidents.tsv" class="export-link" href="#" data-table="incident_table">TSV</a> or <a download="incidents.csv" class="export-link" href="#" data-table="incident_table" data-delimiter=",">CSV</a></div><br />
<div id='incidents_table'>
</div>

{% endblock %}