fir/urls.py
from pkgutil import find_loader
from django.conf.urls import include, url
from django.contrib import admin

from fir.config.base import INSTALLED_APPS
from incidents import views

# urls for core FIR components
urlpatterns = [
    url(r'^incidents/', include('incidents.urls', namespace='incidents')),
    url(r'^search/$', views.search, name='search'),
    url(r'^events/', include('incidents.custom_urls.events', namespace='events')),
    url(r'^login/', views.user_login, name='login'),            # have a "main module"
    url(r'^logout/', views.user_logout, name='logout'),         # main module
    url(r'^stats/', include('incidents.custom_urls.stats', namespace='stats')),
    url(r'^ajax/', include('incidents.custom_urls.ajax', namespace='ajax')),
    url(r'^user/', include('incidents.custom_urls.user', namespace='user')),
    url(r'^dashboard/', include('incidents.custom_urls.dashboard', namespace='dashboard')),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^$', views.dashboard_main),
]

for app in INSTALLED_APPS:
    if app.startswith('fir_'):
        app_name = app[4:]
        app_urls = '{}.urls'.format(app)
        if find_loader(app_urls):
            urlpatterns.append(url('^{}/'.format(app_name), include(app_urls, namespace=app_name)))

fir_api/urls.py
from django.conf.urls import include, url
from rest_framework import routers
from rest_framework.authtoken import views as token_views

from fir_api import views

# automatic URL routing for API
# include login URLs for the browsable API.
router = routers.DefaultRouter(trailing_slash=False)

router.register(r'users', views.UserViewSet)
router.register(r'incidents', views.IncidentViewSet)
router.register(r'artifacts', views.ArtifactViewSet)
router.register(r'files', views.FileViewSet)

# urls for core FIR components
urlpatterns = [
    url(r'^', include(router.urls)),
    url(r'^token/', token_views.obtain_auth_token),
]

fir_artifacts/urls.py
from django.conf.urls import url

from fir_artifacts import views

urlpatterns = [
    url(r'^(?P<artifact_id>\d+)/detach/(?P<relation_name>\w+)/(?P<relation_id>\d+)/$', views.detach_artifact, name='detach'),
    url(r'^(?P<artifact_id>\d+)/correlations/$', views.artifacts_correlations, name='correlations'),
    url(r'^files/(?P<content_type>\d+)/upload/(?P<object_id>\d+)/$', views.upload_file, name='upload_file'),
    url(r'^files/(?P<content_type>\d+)/archive/(?P<object_id>\d+)/$', views.download_archive, name='download_archive'),
    url(r'^files/(?P<file_id>\d+)/remove/$', views.remove_file, name='remove_file'),
    url(r'^files/(?P<file_id>\d+)/download/$', views.download, name='download_file'),
]

fir_artifacts/models.py
import hashlib
import os
from django.db import models
from fir_plugins.models import ManyLinkableModel, OneLinkableModel


class ArtifactBlacklistItem(models.Model):
    type = models.CharField(max_length=20)
    value = models.CharField(max_length=200)

    def __unicode__(self):
        return self.value


class Artifact(ManyLinkableModel):
    type = models.CharField(max_length=20)
    value = models.TextField()

    def __unicode__(self):
        display = self.value
        if self.relations.count() > 1:
            display += " (%s)" % self.relations.count()
        return display


def upload_path(instance, filename):
    return "%s_%s/%s" % (instance.content_type.model, instance.object_id, filename)


class File(OneLinkableModel):

    hashes = models.ManyToManyField('fir_artifacts.Artifact', blank=True)
    description = models.CharField(max_length=256)
    file = models.FileField(upload_to=upload_path)
    date = models.DateTimeField(auto_now_add=True)

    def __unicode__(self):
        return unicode(self.file.name)

    def getfilename(self):
        return os.path.basename(self.file.name)

    def get_hashes(self):
        hashes = dict((k, None) for k in ['md5', 'sha1', 'sha256'])
        content = self.file.read()
        for algo in hashes:
            m = hashlib.new(algo)
            m.update(content)
            hashes[algo] = m.hexdigest()
        return hashes

fir_artifacts/views.py
from django.contrib.auth.decorators import login_required, user_passes_test
from django.core.exceptions import PermissionDenied
from django.http import Http404
from django.shortcuts import get_object_or_404, render, redirect
from django.conf import settings
from fir_artifacts.files import do_download_archive, do_download, do_upload_file, do_remove_file

from incidents.views import is_incident_viewer

from fir_artifacts.models import Artifact


@login_required
@user_passes_test(is_incident_viewer)
def artifacts_correlations(request, artifact_id):
    a = get_object_or_404(Artifact, pk=artifact_id)
    correlations = a.relations_for_user(request.user).group()
    if all([not link_type.objects.exists() for link_type in correlations.values()]):
        raise PermissionDenied
    return render(request, 'fir_artifacts/correlation_list.html', {'correlations': correlations,
                                                                   'artifact': a,
                                                                   'incident_show_id': settings.INCIDENT_SHOW_ID})


@login_required
def detach_artifact(request, artifact_id, relation_name, relation_id):
    a = get_object_or_404(Artifact, pk=artifact_id)
    relation = getattr(a, relation_name, None)
    if relation is None:
        raise Http404("Unknown relation")
    try:
        related = relation.get(pk=relation_id)
    except:
        raise Http404("Unknown related object")
    if not request.user.has_perm('incidents.handle_incidents', obj=related):
        raise PermissionDenied()
    a.relations.remove(related)
    if a.relations.count() == 0:
        a.delete()
    return redirect('%s:details' % relation_name, relation_id)


@login_required
def download_archive(request, content_type, object_id):
    return do_download_archive(request, content_type, object_id)


@login_required
def download(request, file_id):
    return do_download(request, file_id)


@login_required
def upload_file(request, content_type, object_id):
    return do_upload_file(request, content_type, object_id)


@login_required
def remove_file(request, file_id):
    return do_remove_file(request, file_id)

fir_artifacts/templates/fir_artifacts/plugins/details_sidebar.html
{% load i18n %}
{% load fir_plugins %}
{% load fir_artifacts %}
{% load authorization %}
{%  has_perm 'incidents.handle_incidents' obj=event as can_handle_incident %}
<div class='widget {% if event.file_set.count == 0 %}hidden{% endif%}' id='details-files'>
<h4 class='widget'>{%  trans "Related files" %}</h4>
    {% if event.file_set.count > 0 %}
        <table class='table table-condensed files fixed'>
            <thead>
                <tr>
                    <th class="date-column">{%  trans "Date" %}</th>
                    <th>{%  trans "File" %}</th>
                    <th>{%  trans "Description" %}</th>
                    <th class="icon-column"></th>
                </tr>
            </thead>
            {% for file in event.file_set.all %}
                <tr>
                    <td>{{file.date}}</td>
                    <td>
                        <a href="{% url 'artifacts:download_file' file.id %}">
                            {{ file.getfilename }}
                        </a>
                    </td>
                    <td>{{ file.description }}</td>
                    <td class="icon-column">
                        {% if can_handle_incident %}
                        <form id='details-file-delete' action="{% url 'artifacts:remove_file' file.id %}" method='POST'>
                            {% csrf_token %}
                            <button type="submit" class="btn btn-link btn-xs icon">
                                <i class="glyphicon glyphicon-trash"></i>
                            </button>
                        </form>
                        {% endif %}
                    </td>
                </tr>
            {% endfor %}
        </table>
    {% endif %}
    {% if can_handle_incident %}
    <form id='upload_form' enctype="multipart/form-data" action="{% url 'artifacts:upload_file' event|content_type event.id %}" method='POST'>
        {% csrf_token %}
        <div class='upload'>
            <span>{%  trans "Dropzone" %}</span>
            <input type="file" name="file" id="id_file" multiple />
        </div>
        <table id='filetable' class='table table-condensed'></table>
    </form>
    <a class="btn btn-sm btn-default" href="#" onclick='javascript:$("#id_file").click();'>
        <i class="glyphicon glyphicon-file"></i> {%  trans "Browse..." %}
    </a>
    <a class="btn btn-sm btn-default" href="#" onclick='javascript:$("#upload_form").submit();'>
        <i class="glyphicon glyphicon-upload"></i> {%  trans "Upload files" %}
    </a>
    {% endif %}
    {% if event.file_set.count > 0 %}
        <a class="btn btn-sm btn-default" href="{% url 'artifacts:download_archive' event|content_type event.id %}">
            <i class="glyphicon glyphicon-download-alt"></i> {%  trans "Download archive" %}
        </a>
    {% endif %}
</div>


{% if correlated_count > 0 %}
	<div class="widget">
		<h4 class='widget'>{%  trans "Correlated Artifacts" %}</h4>

		<div class='' id='sidebar_artifacts'>
			<table class='table table-condensed artifacts-table artifacts fixed'>
    <thead>
        <tr>
            <th class='head'>{%  trans "Type" %}</th>
            <th>{%  trans "Values" %}</th>
        </tr>
    </thead>
    {% for artifact_type in artifacts %}
        {{ artifact_type|display_correlated_artifact:request }}
    {% endfor %}
</table>
		</div>
	</div>
{% endif %}

fir_artifacts/templates/fir_artifacts/plugins/details_static.html
{% load staticfiles %}
<script src="{% static "fir_artifacts/js/tooltips.js" %}"></script>

fir_artifacts/templates/fir_artifacts/plugins/details_tab.html
{% load i18n %}

{% if artifacts_count > 0 %}
	<li>
		<a href='#tab_artifacts' data-toggle='tab'>
			{% trans "Artifacts" %} ({{ artifacts_count }})
		</a>
	</li>
{% endif %}

fir_artifacts/templates/fir_artifacts/plugins/details_tab_content.html
{% load i18n %}
{% load fir_artifacts %}

<div class='tab-pane' id='tab_artifacts'>
	<div class='' id='artifacts'>
		{% if event.file_set.count > 0 %}
	<table class='table table-condensed files-table files fixed'>
		<tr><th>{%  trans "Filename" %}</th><th>SHA-256</th><th>SHA-1</th><th>MD5</th></tr>
		{% for f in event.file_set.all %}
			<tr><td>{{ f.getfilename }}</td>{{ f.hashes|hashes_line }}</tr>
		{% endfor %}
	</table>

	<h3>{%  trans "Other artifacts" %}</h3>
{% endif %}

<table class='table table-condensed artifacts-table artifacts'>
	<thead>
		<th class='head'>{%  trans "Type" %}</th>
		<th>{%  trans "Values" %}</th>
	</thead>
	{% for artifact_type in artifacts %}
		{{ artifact_type|display_artifact:request }}
	{% endfor %}
</table>
	</div>
</div>