fir/urls.py
from pkgutil import find_loader
from django.conf.urls import include, url
from django.contrib import admin

from fir.config.base import INSTALLED_APPS
from incidents import views

# urls for core FIR components
urlpatterns = [
    url(r'^incidents/', include('incidents.urls', namespace='incidents')),
    url(r'^search/$', views.search, name='search'),
    url(r'^events/', include('incidents.custom_urls.events', namespace='events')),
    url(r'^login/', views.user_login, name='login'),            # have a "main module"
    url(r'^logout/', views.user_logout, name='logout'),         # main module
    url(r'^stats/', include('incidents.custom_urls.stats', namespace='stats')),
    url(r'^ajax/', include('incidents.custom_urls.ajax', namespace='ajax')),
    url(r'^user/', include('incidents.custom_urls.user', namespace='user')),
    url(r'^dashboard/', include('incidents.custom_urls.dashboard', namespace='dashboard')),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^$', views.dashboard_main),
]

for app in INSTALLED_APPS:
    if app.startswith('fir_'):
        app_name = app[4:]
        app_urls = '{}.urls'.format(app)
        if find_loader(app_urls):
            urlpatterns.append(url('^{}/'.format(app_name), include(app_urls, namespace=app_name)))

fir_api/urls.py
from django.conf.urls import include, url
from rest_framework import routers
from rest_framework.authtoken import views as token_views

from fir_api import views

# automatic URL routing for API
# include login URLs for the browsable API.
router = routers.DefaultRouter(trailing_slash=False)

router.register(r'users', views.UserViewSet)
router.register(r'incidents', views.IncidentViewSet)
router.register(r'artifacts', views.ArtifactViewSet)
router.register(r'files', views.FileViewSet)

# urls for core FIR components
urlpatterns = [
    url(r'^', include(router.urls)),
    url(r'^token/', token_views.obtain_auth_token),
]

fir_nuggets/urls.py
from django.conf.urls import url

from fir_nuggets import views

urlpatterns = [
    url(r'^(?P<event_id>\d+)/list', views.list, name='list'),
    url(r'^(?P<event_id>\d+)/new', views.new, name='new'),
    url(r'^edit/(?P<nugget_id>\d+)', views.edit, name='edit'),
    url(r'^delete/(?P<nugget_id>\d+)', views.delete, name='delete'),
]

incidents/urls.py
from django.conf.urls import url

from incidents import views

urlpatterns = [
    url(r'^$', views.index, {'is_incident': True}, name='index'),
    url(r'^all/$', views.incidents_all, name='all'),
    url(r'^(?P<incident_id>\d+)/$', views.details, name='details'),
    url(r'^(?P<incident_id>\d+)/followup/$', views.followup, name='followup'),
    url(r'^(?P<incident_id>\d+)/comment/$', views.comment, name='comment'),
    url(r'^(?P<incident_id>\d+)/comment/(?P<comment_id>\d+)/delete/$', views.delete_comment, name='delete_comment'),
    url(r'^(?P<incident_id>\d+)/edit/$', views.edit_incident, name='edit'),
    url(r'^(?P<incident_id>\d+)/delete/$', views.delete_incident, name='delete'),
    url(r'^(?P<incident_id>\d+)/status/(?P<status>[OBC])$', views.change_status, name='change_status'),
    url(r'^(?P<incident_id>\d+)/attribute$', views.add_attribute, name='add_attribute'),
    url(r'^(?P<incident_id>\d+)/attribute/(?P<attribute_id>\d+)/delete/$', views.delete_attribute, name='delete_attribute'),
]

incidents/views.py
# -*- coding: utf-8 -*-


# Create your views here.
from django.contrib.auth.forms import PasswordChangeForm
from django.contrib.auth.models import User
from django.contrib.staticfiles import finders
from django.template.response import TemplateResponse
from django.views.decorators.http import require_POST

from incidents.models import IncidentCategory, Incident, Comments, BusinessLine, model_status_changed
from incidents.models import Label, Log, BaleCategory
from incidents.models import Attribute, ValidAttribute, IncidentTemplate, Profile
from incidents.models import IncidentForm, CommentForm
from incidents.authorization.decorator import authorization_required
from fir.config.base import INSTALLED_APPS
import importlib

from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required, user_passes_test
from django.core import serializers
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger

from django.core.urlresolvers import reverse
from django.db.models import Q, Max
from django.http import HttpResponse, HttpResponseServerError
from django.shortcuts import get_object_or_404, render, redirect
from django.template import RequestContext
from json import dumps
from django.template import Template

from django.core.exceptions import ObjectDoesNotExist, PermissionDenied
from django.forms.models import model_to_dict, modelform_factory
from django.utils.translation import ugettext_lazy as _
from django.conf import settings

import re, datetime
from dateutil.relativedelta import *
from dateutil.parser import parse
from bson import json_util

import copy
import math

from fir_artifacts import artifacts as libartifacts

cal = [
    'jan',
    'feb',
    'mar',
    'apr',
    'may',
    'jun',
    'jul',
    'aug',
    'sep',
    'oct',
    'nov',
    'dec',
]

APP_HOOKS = {}

for app in INSTALLED_APPS:
    if app.startswith('fir_'):
        app_name = app[4:]
        try:
            h = importlib.import_module('{}.hooks'.format(app))
            APP_HOOKS[app_name] = h.hooks
        except ImportError:
            pass




# helper =========================================================


def is_incident_handler(user):
    return user.has_perm('incidents.handle_incidents', obj=Incident)


def is_incident_reporter(user):
    return user.has_perm('incidents.handle_incidents', obj=Incident) or user.has_perm('incidents.report_events',
                                                                                      obj=Incident)


def is_incident_viewer(user):
    return user.has_perm('incidents.view_incidents', obj=Incident) or user.has_perm('incidents.report_events',
                                                                                    obj=Incident)


def can_view_statistics(user):
    return user.has_perm('incidents.view_statistics', obj=Incident)


comment_permissions = ['incidents.handle_incidents', ]
if getattr(settings, 'INCIDENT_VIEWER_CAN_COMMENT', False):
    comment_permissions.append('incidents.view_incidents')


# login / logout =================================================


def user_login(request):
    if request.method == "POST":
        username = request.POST['username']
        password = request.POST['password']
        user = authenticate(username=username, password=password)
        if user is not None:
            if not request.POST.get('remember', None):
                request.session.set_expiry(0)

            try:
                Profile.objects.get(user=user)
            except ObjectDoesNotExist:
                profile = Profile()
                profile.user = user
                profile.hide_closed = False
                profile.incident_number = 50
                profile.save()

            if user.is_active:
                login(request, user)
                log("Login success", user)
                init_session(request)
                return redirect('dashboard:main')
            else:
                log("Login attempted from locked account", user)
                return HttpResponse('Account disabled')
        else:
            log("Login failed for "+username, None)
            return render(request, 'incidents/login.html', {'error': 'error'})
    else:
        return render(request, 'incidents/login.html')


def user_logout(request):
    logout(request)
    request.session.flush()
    return redirect('login')


def init_session(request):
    pass
    # Put all the incident templates in the session
    request.session['incident_templates'] = list(IncidentTemplate.objects.exclude(name='default').values('name'))
    request.session['has_incident_templates'] = len(request.session['incident_templates']) > 0
    request.session['can_report_event'] = request.user.has_perm('incidents.handle_incidents', obj=Incident) or \
                                          request.user.has_perm('incidents.report_events', obj=Incident)


# audit trail =====================================================


def log(what, user, incident=None, comment=None):
    # dirty hack to not log when in debug mode
    import sys
    if getattr(settings, 'DEBUG', False):
        print "DEBUG: Not logging"
        return

    log = Log()
    log.what = what
    log.who = user
    log.incident = incident
    log.comment = comment

    log.save()


# incidents =======================================================

@login_required
@authorization_required('incidents.view_incidents', Incident, view_arg='incident_id')
def followup(request, incident_id, authorization_target=None):
    if authorization_target is None:
        i = get_object_or_404(
            Incident.authorization.for_user(request.user, ['incidents.view_incidents', 'incidents.handle_incidents']),
            pk=incident_id)
    else:
        i = authorization_target
    comments = i.comments_set.all().order_by('date')

    return render(
        request,
        'incidents/followup.html',
        {'incident': i, 'comments': comments, 'incident_show_id': settings.INCIDENT_SHOW_ID}
    )


@login_required
@user_passes_test(is_incident_viewer)
def index(request, is_incident=False):
    return render(request, 'events/index-all.html', {'incident_view': is_incident})


@login_required
@user_passes_test(is_incident_viewer)
def incidents_all(request):
    return incident_display(request, Q(is_incident=True))


@login_required
@user_passes_test(is_incident_viewer)
def events_all(request):
    return incident_display(request, Q(is_incident=False), False)


@login_required
@authorization_required('incidents.view_incidents', Incident, view_arg='incident_id')
def details(request, incident_id, authorization_target=None):
    if authorization_target is None:
        i = get_object_or_404(
            Incident.authorization.for_user(request.user, ['incidents.view_incidents', 'incidents.handle_incidents']),
            pk=incident_id)
    else:
        i = authorization_target
    form = CommentForm()
    if not request.user.has_perm('incidents.handle_incidents', obj=i):
        form.fields['action'].queryset = Label.objects.filter(group__name='action').exclude(
            name__in=['Closed', 'Opened', 'Blocked'])

    (artifacts, artifacts_count, correlated_count) = libartifacts.all_for_object(i, user=request.user)

    """
    Temp fix until i figure out how to set this
    """
    valid_attributes = i.category.validattribute_set.all()
    attributes = i.attribute_set.all()

    comments = i.comments_set.all().order_by('date')

    return render(
        request,
        "events/detail-all.html",
        {"event": i,
         "comment_form": form,
         "correlated_count": correlated_count,
         "artifacts_count": artifacts_count,
         "artifacts": artifacts,
         "attributes": attributes,
         "valid_attributes": valid_attributes,
         "comments": comments,
         "incident_show_id": settings.INCIDENT_SHOW_ID}
    )


@login_required
@user_passes_test(is_incident_reporter)
def new_event(request):
    if request.method == 'POST':
        form = IncidentForm(request.POST, for_user=request.user)

        form.status = _('Open')

        if form.is_valid():
            i = form.save(commit=False)

            if not form.cleaned_data['is_major']:
                i.is_major = form.cleaned_data['category'].is_major

            if i.is_major:
                i.is_incident = True

            i.opened_by = request.user
            i.save()
            form.save_m2m()
            i.refresh_main_business_lines()
            i.done_creating()

            if i.is_incident:
                return redirect("incidents:details", incident_id=i.id)
            else:
                return redirect("events:details", incident_id=i.id)

    else:
        template = request.GET.get('template', 'default')
        try:
            template = IncidentTemplate.objects.get(name=template)
            data = model_to_dict(template)
            data['description'] = Template(data['description']).render(RequestContext(request))
        except ObjectDoesNotExist:
            data = {}
        form = IncidentForm(initial=data, for_user=request.user)

    return render(request, 'events/new.html', {'form': form, 'mode': 'new'})


def diff(incident, form):
    comments = []
    for i in form:
        # skip the following fields from diff
        if i in ['description', 'concerned_business_lines', 'main_business_lines']:
            continue

        new = form[i]
        old = getattr(incident, i)

        if new != old:

            label = i

            if i == 'is_major':
                label = 'major'
            if i == 'concerned_business_lines':
                label = "business lines"
            if i == 'main_business_line':
                label = "main business line"
            if i == 'is_incident':
                label = 'incident'

            if old == "O":
                old = 'Open'
            if old == "C":
                old = 'Closed'

incidents/templates/base.html
{% load fir_plugins %}
{% load i18n %}
{% load staticfiles %}
{% load authorization %}
<!DOCTYPE html>
<html lang="{{ LANGUAGE_CODE }}">
  <head>
    <meta charset="utf-8">
    <title>{%block title%}FIR{%endblock%}</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no">
    <meta name="description" content="">
    <meta name="author" content="">


    <!-- Le styles -->
    <link href="{% static "css/jquery-ui.min.css" %}" rel="stylesheet">
    <link href="{% static "css/bootstrap.min.css" %}" rel="stylesheet">
    <link href="{% static "css/bootstrap-datetimepicker.min.css" %}" rel="stylesheet">
    <link href="{% static "custom_css/fir.css" %}" rel="stylesheet">
    {% block custom_js_top %}{% endblock %}
    {% block custom_css %}{% endblock%}

    <!-- HTML5 shim, for IE6-8 support of HTML5 elements -->
    <!--[if lt IE 9]>
      <script src="{% static "js/html5.js" %}"></script>
    <![endif]-->

    <!-- Fav and touch icons -->
    <link rel="shortcut icon" href="{% static "img/favicon.png" %}">
  </head>

  <body>

    <div class="navbar-sm">
      <nav class="navbar navbar-inverse navbar-fixed-top">
        <div class="container-fluid">
          <div class="navbar-header">
            <button id="header-collapse" type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar-collapse">
              <span class="sr-only">Toggle navigation</span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="{% url 'dashboard:main' %}">FIR</a>
          </div>

          <div class="collapse navbar-collapse" id="navbar-collapse">
            <ul class="nav navbar-nav">
              {% if request.session.can_report_event %}
              <li>
                <div class="btn-group navbar-btn">
                  <button class="btn btn-danger" onclick="javascript:location.href='{% url 'events:new' %}'">
                    {% trans "New event" %} <span class="glyphicon glyphicon-fire"></span>
                  </button>
                  {% if request.session.has_incident_templates %}
                  <button type="button" class="btn btn-danger dropdown-toggle" data-toggle="dropdown">
                    <span class="caret"></span>
                  </button>
                  <ul class="dropdown-menu">
                    {% for template in request.session.incident_templates %}
                    <li>
                      <a href="{% url 'events:new' %}?template={{ template.name }}">
                        {{ template.name }}
                      </a>
                    </li>
                    {% endfor %}
                    <li class="divider"></li>
                    <li><a href="{% url 'events:new' %}">{% trans "Default" %}</a></li>
                  </ul>
                  {% endif %}
                </div>
              </li>
              {% endif %}
              <li id='dashboard-nav'><a href="{% url 'dashboard:main' %}">{% trans "Dashboard" %}</a></li>
              <li id='incidents-nav'><a href="{% url 'incidents:index' %}">{% trans "Incidents"%}</a></li>
              <li id='events-nav'><a href="{% url 'events:index' %}">{% trans "Events" %}</a></li>
            {% plugin_point 'base_navbar' %}
              {% has_perm 'incidents.view_statistics' model='incidents.Incident' as can_view_statistics %}
              {% if can_view_statistics %}
              <li id='incidents-nav' class='dropdown'>
                <a class='dropdown-toggle' data-toggle='dropdown' href="#">{% trans "Stats" %}</a>
                <ul class='dropdown-menu'>
                  <li><a href="{% url 'stats:yearly' %}">{% trans "Yearly" %}</a></li>
                  <li><a href="{% url 'stats:quarterly_bl_stats_default' %}">{% trans "Quarterly" %}</a></li>
                  <li><a href="{% url 'stats:yearly_compare' %}">{% trans "Compare with previous year" %}</a></li>
                  <li><a href="{%url 'stats:quarterly_major' %}">{% trans "Major incidents" %}</a></li>
                  <li><a href="{%url 'stats:sandbox' %}">{% trans "Sandbox" %} <i class='glyphicon glyphicon-asterisk'></i></a></li>
                  <li><a href="{%url 'stats:attributes' %}">{% trans "Attributes" %}</a></li>
                </ul>
              </li>
              {% endif %}
            </ul>
            <ul class="nav navbar-nav navbar-right">
              <li>
                <div class='usergreet'>
                  {% trans "Currently logged in as" %} <a href="{% url 'user:profile' %}"><strong>{{ user }}</strong></a> [
                    <a href="{% url 'logout' %}">{% trans "logout" %}</a>
                  ]
                  {% if user.is_staff %}
                    [ <a href="{% url 'admin:index' %}">{% trans "Admin" %}</a> ]
                  {% endif %}
                </div>
              </li>
            </ul>

              <div id="search-bar" class="form-group" style="display:inline;">
                <div class="input-group" style="display:table;">
                  <span class="input-group-addon" style="width:1%;"><span class="glyphicon glyphicon-search"></span></span>
                  <form method="GET" action="{% url 'search' %}">
                    <input class="form-control" name="q" placeholder="{% trans 'search...' %}" autocomplete="off" type="text" {% if query_string %}value='{{query_string}}'{% endif %}>
                  </form>
                </div>
              </div>

          </div>
        </div>
      </nav>
    </div>

    <div class="container-fluid">
      {% block header %}{% endblock %}
      {% block content %}{% endblock %}
    </div>

    <!-- Le javascript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <script type="text/javascript" src="{% static "js/jquery.min.js" %}"></script>
    <script src="{% static "js/jquery-ui.min.js" %}"></script>
    <script type="text/javascript" src="{% static "momentjs/moment.min.js" %}"></script>
    <script type="text/javascript" src="{% static "js/bootstrap.min.js" %}"></script>
    <script type="text/javascript" src="{% static "js/bootstrap-datetimepicker.min.js" %}"></script>
    <script type="text/javascript" src="{% static "custom_js/ajax.js" %}"></script>
    <script type="text/javascript" src="{% static "custom_js/auto_ajax.js" %}"></script>

    {% block custom_js %}{% endblock %}

    <footer class="hidden-xs">
      <div>
        FIR - Fast Incident Response - <a href='https://cert.societegenerale.com/'>CERT Soci&eacute;t&eacute; G&eacute;n&eacute;rale {% now "Y"%}</a> &copy; bug reports go to <a href='https://github.com/certsocietegenerale/FIR' target='blank'>the GitHub repository</a>
      </div>
    </footer>
  </body>
</html>